### ISSUE TITLE
[optimization] Use nextTermStart instead of termEnd

### ISSUE THREAD

**Issue by spengrah** [Hats-Protocol/jokerace-eligibility#2]
that would allow you to do `if (block.timestamp < nextTermStart)`, saving 1 operation relative to https://github.com/Hats-Protocol/jokerace-eligibility/blob/f7dc50a8988ac487172ea330ca4250c0a65f84e4/src/JokeraceEligibility.sol#L118

the tradeoff is that we have to spend 1 additional operation in `reelectionAllowed()`, but that will very likely be called many fewer times than `getWearerStatus()`

**Comment by gershido** [comment]
Fixed in #11. Used the same name `termEnd` instead of `nextTermStart` because the next term start is only known when a reelection is set. 

https://github.com/Hats-Protocol/jokerace-eligibility/blob/52c04111c2be0b90971393bdec3524d9d64ef3ac/src/JokeraceEligibility.sol#L113-L118

https://github.com/Hats-Protocol/jokerace-eligibility/blob/52c04111c2be0b90971393bdec3524d9d64ef3ac/src/JokeraceEligibility.sol#L188-L190

**Comment by spengrah** [comment]
> Used the same name termEnd

@gershido that's fine as long as its documented well, which I see it is :)
